import 'package:drift/drift.dart';
import 'app_database.dart';

final List<SurahsCompanion> initialSurahsList = [
  SurahsCompanion.insert(
    id: const Value(1),
    number: 1,
    nameArabic: 'الفاتحة',
    namePersian: 'حمد',
    nameEnglish: 'Al-Fatihah',
    revelationType: 'Makki',
    verseCount: 7,
  ),
  SurahsCompanion.insert(
    id: const Value(2),
    number: 2,
    nameArabic: 'البقرة',
    namePersian: 'بقره',
    nameEnglish: 'Al-Baqarah',
    revelationType: 'Madani',
    verseCount: 286,
  ),
  SurahsCompanion.insert(
    id: const Value(3),
    number: 3,
    nameArabic: 'آل عمران',
    namePersian: 'آل عمران',
    nameEnglish: 'Ali \'Imran',
    revelationType: 'Madani',
    verseCount: 200,
  ),
  SurahsCompanion.insert(
    id: const Value(4),
    number: 4,
    nameArabic: 'النساء',
    namePersian: 'نساء',
    nameEnglish: 'An-Nisa',
    revelationType: 'Madani',
    verseCount: 176,
  ),
  SurahsCompanion.insert(
    id: const Value(5),
    number: 5,
    nameArabic: 'المائدة',
    namePersian: 'مائده',
    nameEnglish: 'Al-Ma\'idah',
    revelationType: 'Madani',
    verseCount: 120,
  ),
  SurahsCompanion.insert(
    id: const Value(6),
    number: 6,
    nameArabic: 'الأنعام',
    namePersian: 'انعام',
    nameEnglish: 'Al-An\'am',
    revelationType: 'Makki',
    verseCount: 165,
  ),
  SurahsCompanion.insert(
    id: const Value(7),
    number: 7,
    nameArabic: 'الأعراف',
    namePersian: 'اعراف',
    nameEnglish: 'Al-A\'raf',
    revelationType: 'Makki',
    verseCount: 206,
  ),
  SurahsCompanion.insert(
    id: const Value(8),
    number: 8,
    nameArabic: 'الأنفال',
    namePersian: 'انفال',
    nameEnglish: 'Al-Anfal',
    revelationType: 'Madani',
    verseCount: 75,
  ),
  SurahsCompanion.insert(
    id: const Value(9),
    number: 9,
    nameArabic: 'التوبة',
    namePersian: 'توبه',
    nameEnglish: 'At-Tawbah',
    revelationType: 'Madani',
    verseCount: 129,
  ),
  SurahsCompanion.insert(
    id: const Value(10),
    number: 10,
    nameArabic: 'يونس',
    namePersian: 'یونس',
    nameEnglish: 'Yunus',
    revelationType: 'Makki',
    verseCount: 109,
  ),
  SurahsCompanion.insert(
    id: const Value(11),
    number: 11,
    nameArabic: 'هود',
    namePersian: 'هود',
    nameEnglish: 'Hud',
    revelationType: 'Makki',
    verseCount: 123,
  ),
  SurahsCompanion.insert(
    id: const Value(12),
    number: 12,
    nameArabic: 'يوسف',
    namePersian: 'یوسف',
    nameEnglish: 'Yusuf',
    revelationType: 'Makki',
    verseCount: 111,
  ),
  SurahsCompanion.insert(
    id: const Value(13),
    number: 13,
    nameArabic: 'الرعد',
    namePersian: 'رعد',
    nameEnglish: 'Ar-Ra\'d',
    revelationType: 'Madani',
    verseCount: 43,
  ),
  SurahsCompanion.insert(
    id: const Value(14),
    number: 14,
    nameArabic: 'إبراهيم',
    namePersian: 'ابراهیم',
    nameEnglish: 'Ibrahim',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: const Value(15),
    number: 15,
    nameArabic: 'الحجر',
    namePersian: 'حجر',
    nameEnglish: 'Al-Hijr',
    revelationType: 'Makki',
    verseCount: 99,
  ),
  SurahsCompanion.insert(
    id: const Value(16),
    number: 16,
    nameArabic: 'النحل',
    namePersian: 'نحل',
    nameEnglish: 'An-Nahl',
    revelationType: 'Makki',
    verseCount: 128,
  ),
  SurahsCompanion.insert(
    id: const Value(17),
    number: 17,
    nameArabic: 'الإسراء',
    namePersian: 'اسراء',
    nameEnglish: 'Al-Isra',
    revelationType: 'Makki',
    verseCount: 111,
  ),
  SurahsCompanion.insert(
    id: const Value(18),
    number: 18,
    nameArabic: 'الكهف',
    namePersian: 'کهف',
    nameEnglish: 'Al-Kahf',
    revelationType: 'Makki',
    verseCount: 110,
  ),
  SurahsCompanion.insert(
    id: const Value(19),
    number: 19,
    nameArabic: 'مريم',
    namePersian: 'مریم',
    nameEnglish: 'Maryam',
    revelationType: 'Makki',
    verseCount: 98,
  ),
  SurahsCompanion.insert(
    id: const Value(20),
    number: 20,
    nameArabic: 'طه',
    namePersian: 'طه',
    nameEnglish: 'Taha',
    revelationType: 'Makki',
    verseCount: 135,
  ),
  SurahsCompanion.insert(
    id: const Value(21),
    number: 21,
    nameArabic: 'الأنبياء',
    namePersian: 'انبیاء',
    nameEnglish: 'Al-Anbiya',
    revelationType: 'Makki',
    verseCount: 112,
  ),
  SurahsCompanion.insert(
    id: const Value(22),
    number: 22,
    nameArabic: 'الحج',
    namePersian: 'حج',
    nameEnglish: 'Al-Hajj',
    revelationType: 'Madani',
    verseCount: 78,
  ),
  SurahsCompanion.insert(
    id: const Value(23),
    number: 23,
    nameArabic: 'المؤمنون',
    namePersian: 'مؤمنون',
    nameEnglish: 'Al-Mu\'minun',
    revelationType: 'Makki',
    verseCount: 118,
  ),
  SurahsCompanion.insert(
    id: const Value(24),
    number: 24,
    nameArabic: 'النور',
    namePersian: 'نور',
    nameEnglish: 'An-Nur',
    revelationType: 'Madani',
    verseCount: 64,
  ),
  SurahsCompanion.insert(
    id: const Value(25),
    number: 25,
    nameArabic: 'الفرقان',
    namePersian: 'فرقان',
    nameEnglish: 'Al-Furqan',
    revelationType: 'Makki',
    verseCount: 77,
  ),
  SurahsCompanion.insert(
    id: const Value(26),
    number: 26,
    nameArabic: 'الشعراء',
    namePersian: 'شعراء',
    nameEnglish: 'Ash-Shu\'ara',
    revelationType: 'Makki',
    verseCount: 227,
  ),
  SurahsCompanion.insert(
    id: const Value(27),
    number: 27,
    nameArabic: 'النمل',
    namePersian: 'نمل',
    nameEnglish: 'An-Naml',
    revelationType: 'Makki',
    verseCount: 93,
  ),
  SurahsCompanion.insert(
    id: const Value(28),
    number: 28,
    nameArabic: 'القصص',
    namePersian: 'قصص',
    nameEnglish: 'Al-Qasas',
    revelationType: 'Makki',
    verseCount: 88,
  ),
  SurahsCompanion.insert(
    id: const Value(29),
    number: 29,
    nameArabic: 'العنكبوت',
    namePersian: 'عنکبوت',
    nameEnglish: 'Al-\'Ankabut',
    revelationType: 'Makki',
    verseCount: 69,
  ),
  SurahsCompanion.insert(
    id: const Value(30),
    number: 30,
    nameArabic: 'الروم',
    namePersian: 'روم',
    nameEnglish: 'Ar-Rum',
    revelationType: 'Makki',
    verseCount: 60,
  ),
  SurahsCompanion.insert(
    id: const Value(31),
    number: 31,
    nameArabic: 'لقمان',
    namePersian: 'لقمان',
    nameEnglish: 'Luqman',
    revelationType: 'Makki',
    verseCount: 34,
  ),
  SurahsCompanion.insert(
    id: const Value(32),
    number: 32,
    nameArabic: 'السجدة',
    namePersian: 'سجده',
    nameEnglish: 'As-Sajdah',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: const Value(33),
    number: 33,
    nameArabic: 'الأحزاب',
    namePersian: 'احزاب',
    nameEnglish: 'Al-Ahzab',
    revelationType: 'Madani',
    verseCount: 73,
  ),
  SurahsCompanion.insert(
    id: const Value(34),
    number: 34,
    nameArabic: 'سبإ',
    namePersian: 'سبأ',
    nameEnglish: 'Saba',
    revelationType: 'Makki',
    verseCount: 54,
  ),
  SurahsCompanion.insert(
    id: const Value(35),
    number: 35,
    nameArabic: 'فاطر',
    namePersian: 'فاطر',
    nameEnglish: 'Fatir',
    revelationType: 'Makki',
    verseCount: 45,
  ),
  SurahsCompanion.insert(
    id: const Value(36),
    number: 36,
    nameArabic: 'يس',
    namePersian: 'یس',
    nameEnglish: 'Ya-Sin',
    revelationType: 'Makki',
    verseCount: 83,
  ),
  SurahsCompanion.insert(
    id: const Value(37),
    number: 37,
    nameArabic: 'الصافات',
    namePersian: 'صافات',
    nameEnglish: 'As-Saffat',
    revelationType: 'Makki',
    verseCount: 182,
  ),
  SurahsCompanion.insert(
    id: const Value(38),
    number: 38,
    nameArabic: 'ص',
    namePersian: 'ص',
    nameEnglish: 'Sad',
    revelationType: 'Makki',
    verseCount: 88,
  ),
  SurahsCompanion.insert(
    id: const Value(39),
    number: 39,
    nameArabic: 'الزمر',
    namePersian: 'زمر',
    nameEnglish: 'Az-Zumar',
    revelationType: 'Makki',
    verseCount: 75,
  ),
  SurahsCompanion.insert(
    id: const Value(40),
    number: 40,
    nameArabic: 'غافر',
    namePersian: 'غافر',
    nameEnglish: 'Ghafir',
    revelationType: 'Makki',
    verseCount: 85,
  ),
  SurahsCompanion.insert(
    id: const Value(41),
    number: 41,
    nameArabic: 'فصلت',
    namePersian: 'فصلت',
    nameEnglish: 'Fussilat',
    revelationType: 'Makki',
    verseCount: 54,
  ),
  SurahsCompanion.insert(
    id: const Value(42),
    number: 42,
    nameArabic: 'الشورى',
    namePersian: 'شوری',
    nameEnglish: 'Ash-Shura',
    revelationType: 'Makki',
    verseCount: 53,
  ),
  SurahsCompanion.insert(
    id: const Value(43),
    number: 43,
    nameArabic: 'الزخرف',
    namePersian: 'زخرف',
    nameEnglish: 'Az-Zukhruf',
    revelationType: 'Makki',
    verseCount: 89,
  ),
  SurahsCompanion.insert(
    id: const Value(44),
    number: 44,
    nameArabic: 'الدخان',
    namePersian: 'دخان',
    nameEnglish: 'Ad-Dukhan',
    revelationType: 'Makki',
    verseCount: 59,
  ),
  SurahsCompanion.insert(
    id: const Value(45),
    number: 45,
    nameArabic: 'الجاثية',
    namePersian: 'جاثیه',
    nameEnglish: 'Al-Jathiyah',
    revelationType: 'Makki',
    verseCount: 37,
  ),
  SurahsCompanion.insert(
    id: const Value(46),
    number: 46,
    nameArabic: 'الأحقاف',
    namePersian: 'احقاف',
    nameEnglish: 'Al-Ahqaf',
    revelationType: 'Makki',
    verseCount: 35,
  ),
  SurahsCompanion.insert(
    id: const Value(47),
    number: 47,
    nameArabic: 'محمد',
    namePersian: 'محمد',
    nameEnglish: 'Muhammad',
    revelationType: 'Madani',
    verseCount: 38,
  ),
  SurahsCompanion.insert(
    id: const Value(48),
    number: 48,
    nameArabic: 'الفتح',
    namePersian: 'فتح',
    nameEnglish: 'Al-Fath',
    revelationType: 'Madani',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: const Value(49),
    number: 49,
    nameArabic: 'الحجرات',
    namePersian: 'حجرات',
    nameEnglish: 'Al-Hujurat',
    revelationType: 'Madani',
    verseCount: 18,
  ),
  SurahsCompanion.insert(
    id: const Value(50),
    number: 50,
    nameArabic: 'ق',
    namePersian: 'ق',
    nameEnglish: 'Qaf',
    revelationType: 'Makki',
    verseCount: 45,
  ),
  SurahsCompanion.insert(
    id: const Value(51),
    number: 51,
    nameArabic: 'الذاريات',
    namePersian: 'ذاریات',
    nameEnglish: 'Adh-Dhariyat',
    revelationType: 'Makki',
    verseCount: 60,
  ),
  SurahsCompanion.insert(
    id: const Value(52),
    number: 52,
    nameArabic: 'الطور',
    namePersian: 'طور',
    nameEnglish: 'At-Tur',
    revelationType: 'Makki',
    verseCount: 49,
  ),
  SurahsCompanion.insert(
    id: const Value(53),
    number: 53,
    nameArabic: 'النجم',
    namePersian: 'نجم',
    nameEnglish: 'An-Najm',
    revelationType: 'Makki',
    verseCount: 62,
  ),
  SurahsCompanion.insert(
    id: const Value(54),
    number: 54,
    nameArabic: 'القمر',
    namePersian: 'قمر',
    nameEnglish: 'Al-Qamar',
    revelationType: 'Makki',
    verseCount: 55,
  ),
  SurahsCompanion.insert(
    id: const Value(55),
    number: 55,
    nameArabic: 'الرحمن',
    namePersian: 'الرحمن',
    nameEnglish: 'Ar-Rahman',
    revelationType: 'Madani',
    verseCount: 78,
  ),
  SurahsCompanion.insert(
    id: const Value(56),
    number: 56,
    nameArabic: 'الواقعة',
    namePersian: 'واقعه',
    nameEnglish: 'Al-Waqi\'ah',
    revelationType: 'Makki',
    verseCount: 96,
  ),
  SurahsCompanion.insert(
    id: const Value(57),
    number: 57,
    nameArabic: 'الحديد',
    namePersian: 'حدید',
    nameEnglish: 'Al-Hadid',
    revelationType: 'Madani',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: const Value(58),
    number: 58,
    nameArabic: 'المجادلة',
    namePersian: 'مجادله',
    nameEnglish: 'Al-Mujadila',
    revelationType: 'Madani',
    verseCount: 22,
  ),
  SurahsCompanion.insert(
    id: const Value(59),
    number: 59,
    nameArabic: 'الحشر',
    namePersian: 'حشر',
    nameEnglish: 'Al-Hashr',
    revelationType: 'Madani',
    verseCount: 24,
  ),
  SurahsCompanion.insert(
    id: const Value(60),
    number: 60,
    nameArabic: 'الممتحنة',
    namePersian: 'ممتحنه',
    nameEnglish: 'Al-Mumtahanah',
    revelationType: 'Madani',
    verseCount: 13,
  ),
  SurahsCompanion.insert(
    id: const Value(61),
    number: 61,
    nameArabic: 'الصف',
    namePersian: 'صف',
    nameEnglish: 'As-Saff',
    revelationType: 'Madani',
    verseCount: 14,
  ),
  SurahsCompanion.insert(
    id: const Value(62),
    number: 62,
    nameArabic: 'الجمعة',
    namePersian: 'جمعه',
    nameEnglish: 'Al-Jumu\'ah',
    revelationType: 'Madani',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: const Value(63),
    number: 63,
    nameArabic: 'المنافقون',
    namePersian: 'منافقون',
    nameEnglish: 'Al-Munafiqun',
    revelationType: 'Madani',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: const Value(64),
    number: 64,
    nameArabic: 'التغابن',
    namePersian: 'تغابن',
    nameEnglish: 'At-Taghabun',
    revelationType: 'Madani',
    verseCount: 18,
  ),
  SurahsCompanion.insert(
    id: const Value(65),
    number: 65,
    nameArabic: 'الطلاق',
    namePersian: 'طلاق',
    nameEnglish: 'At-Talaq',
    revelationType: 'Madani',
    verseCount: 12,
  ),
  SurahsCompanion.insert(
    id: const Value(66),
    number: 66,
    nameArabic: 'التحريم',
    namePersian: 'تحریم',
    nameEnglish: 'At-Tahrim',
    revelationType: 'Madani',
    verseCount: 12,
  ),
  SurahsCompanion.insert(
    id: const Value(67),
    number: 67,
    nameArabic: 'الملك',
    namePersian: 'ملک',
    nameEnglish: 'Al-Mulk',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: const Value(68),
    number: 68,
    nameArabic: 'القلم',
    namePersian: 'قلم',
    nameEnglish: 'Al-Qalam',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: const Value(69),
    number: 69,
    nameArabic: 'الحاقة',
    namePersian: 'حاقه',
    nameEnglish: 'Al-Haqqah',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: const Value(70),
    number: 70,
    nameArabic: 'المعارج',
    namePersian: 'معارج',
    nameEnglish: 'Al-Ma\'arij',
    revelationType: 'Makki',
    verseCount: 44,
  ),
  SurahsCompanion.insert(
    id: const Value(71),
    number: 71,
    nameArabic: 'نوح',
    namePersian: 'نوح',
    nameEnglish: 'Nuh',
    revelationType: 'Makki',
    verseCount: 28,
  ),
  SurahsCompanion.insert(
    id: const Value(72),
    number: 72,
    nameArabic: 'الجن',
    namePersian: 'جن',
    nameEnglish: 'Al-Jinn',
    revelationType: 'Makki',
    verseCount: 28,
  ),
  SurahsCompanion.insert(
    id: const Value(73),
    number: 73,
    nameArabic: 'المزمل',
    namePersian: 'مزمل',
    nameEnglish: 'Al-Muzzammil',
    revelationType: 'Makki',
    verseCount: 20,
  ),
  SurahsCompanion.insert(
    id: const Value(74),
    number: 74,
    nameArabic: 'المدثر',
    namePersian: 'مدثر',
    nameEnglish: 'Al-Muddaththir',
    revelationType: 'Makki',
    verseCount: 56,
  ),
  SurahsCompanion.insert(
    id: const Value(75),
    number: 75,
    nameArabic: 'القيامة',
    namePersian: 'قیامت',
    nameEnglish: 'Al-Qiyamah',
    revelationType: 'Makki',
    verseCount: 40,
  ),
  SurahsCompanion.insert(
    id: const Value(76),
    number: 76,
    nameArabic: 'الإنسان',
    namePersian: 'انسان',
    nameEnglish: 'Al-Insan',
    revelationType: 'Madani',
    verseCount: 31,
  ),
  SurahsCompanion.insert(
    id: const Value(77),
    number: 77,
    nameArabic: 'المرسلات',
    namePersian: 'مرسلات',
    nameEnglish: 'Al-Mursalat',
    revelationType: 'Makki',
    verseCount: 50,
  ),
  SurahsCompanion.insert(
    id: const Value(78),
    number: 78,
    nameArabic: 'النبإ',
    namePersian: 'نبأ',
    nameEnglish: 'An-Naba',
    revelationType: 'Makki',
    verseCount: 40,
  ),
  SurahsCompanion.insert(
    id: const Value(79),
    number: 79,
    nameArabic: 'النازعات',
    namePersian: 'نازعات',
    nameEnglish: 'An-Nazi\'at',
    revelationType: 'Makki',
    verseCount: 46,
  ),
  SurahsCompanion.insert(
    id: const Value(80),
    number: 80,
    nameArabic: 'عبس',
    namePersian: 'عبس',
    nameEnglish: '\'Abasa',
    revelationType: 'Makki',
    verseCount: 42,
  ),
  SurahsCompanion.insert(
    id: const Value(81),
    number: 81,
    nameArabic: 'التكوير',
    namePersian: 'تکویر',
    nameEnglish: 'At-Takwir',
    revelationType: 'Makki',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: const Value(82),
    number: 82,
    nameArabic: 'الإنفطار',
    namePersian: 'انفطار',
    nameEnglish: 'Al-Infitar',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: const Value(83),
    number: 83,
    nameArabic: 'المطففين',
    namePersian: 'مطففین',
    nameEnglish: 'Al-Mutaffifin',
    revelationType: 'Makki',
    verseCount: 36,
  ),
  SurahsCompanion.insert(
    id: const Value(84),
    number: 84,
    nameArabic: 'الإنشقاق',
    namePersian: 'انشقاق',
    nameEnglish: 'Al-Inshiqaq',
    revelationType: 'Makki',
    verseCount: 25,
  ),
  SurahsCompanion.insert(
    id: const Value(85),
    number: 85,
    nameArabic: 'البروج',
    namePersian: 'بروج',
    nameEnglish: 'Al-Buruj',
    revelationType: 'Makki',
    verseCount: 22,
  ),
  SurahsCompanion.insert(
    id: const Value(86),
    number: 86,
    nameArabic: 'الطارق',
    namePersian: 'طارق',
    nameEnglish: 'At-Tariq',
    revelationType: 'Makki',
    verseCount: 17,
  ),
  SurahsCompanion.insert(
    id: const Value(87),
    number: 87,
    nameArabic: 'الأعلى',
    namePersian: 'اعلی',
    nameEnglish: 'Al-A\'la',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: const Value(88),
    number: 88,
    nameArabic: 'الغاشية',
    namePersian: 'غاشیه',
    nameEnglish: 'Al-Ghashiyah',
    revelationType: 'Makki',
    verseCount: 26,
  ),
  SurahsCompanion.insert(
    id: const Value(89),
    number: 89,
    nameArabic: 'الفجر',
    namePersian: 'فجر',
    nameEnglish: 'Al-Fajr',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: const Value(90),
    number: 90,
    nameArabic: 'البلد',
    namePersian: 'بلد',
    nameEnglish: 'Al-Balad',
    revelationType: 'Makki',
    verseCount: 20,
  ),
  SurahsCompanion.insert(
    id: const Value(91),
    number: 91,
    nameArabic: 'الشمس',
    namePersian: 'شمس',
    nameEnglish: 'Ash-Shams',
    revelationType: 'Makki',
    verseCount: 15,
  ),
  SurahsCompanion.insert(
    id: const Value(92),
    number: 92,
    nameArabic: 'الليل',
    namePersian: 'لیل',
    nameEnglish: 'Al-Layl',
    revelationType: 'Makki',
    verseCount: 21,
  ),
  SurahsCompanion.insert(
    id: const Value(93),
    number: 93,
    nameArabic: 'الضحى',
    namePersian: 'ضحی',
    nameEnglish: 'Ad-Duha',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: const Value(94),
    number: 94,
    nameArabic: 'الشرح',
    namePersian: 'شرح',
    nameEnglish: 'Ash-Sharh',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: const Value(95),
    number: 95,
    nameArabic: 'التين',
    namePersian: 'تین',
    nameEnglish: 'At-Tin',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: const Value(96),
    number: 96,
    nameArabic: 'العلق',
    namePersian: 'علق',
    nameEnglish: 'Al-\'Alaq',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: const Value(97),
    number: 97,
    nameArabic: 'القدر',
    namePersian: 'قدر',
    nameEnglish: 'Al-Qadr',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: const Value(98),
    number: 98,
    nameArabic: 'البينة',
    namePersian: 'بینه',
    nameEnglish: 'Al-Bayyinah',
    revelationType: 'Madani',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: const Value(99),
    number: 99,
    nameArabic: 'الزلزلة',
    namePersian: 'زلزله',
    nameEnglish: 'Az-Zalzalah',
    revelationType: 'Madani',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: const Value(100),
    number: 100,
    nameArabic: 'العاديات',
    namePersian: 'عادیات',
    nameEnglish: 'Al-\'Adiyat',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: const Value(101),
    number: 101,
    nameArabic: 'القارعة',
    namePersian: 'قارعه',
    nameEnglish: 'Al-Qari\'ah',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: const Value(102),
    number: 102,
    nameArabic: 'التكاثر',
    namePersian: 'تکاثر',
    nameEnglish: 'At-Takathur',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: const Value(103),
    number: 103,
    nameArabic: 'العصر',
    namePersian: 'عصر',
    nameEnglish: 'Al-\'Asr',
    revelationType: 'Makki',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: const Value(104),
    number: 104,
    nameArabic: 'الهمزة',
    namePersian: 'همزه',
    nameEnglish: 'Al-Humazah',
    revelationType: 'Makki',
    verseCount: 9,
  ),
  SurahsCompanion.insert(
    id: const Value(105),
    number: 105,
    nameArabic: 'الفيل',
    namePersian: 'فیل',
    nameEnglish: 'Al-Fil',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: const Value(106),
    number: 106,
    nameArabic: 'قريش',
    namePersian: 'قریش',
    nameEnglish: 'Quraysh',
    revelationType: 'Makki',
    verseCount: 4,
  ),
  SurahsCompanion.insert(
    id: const Value(107),
    number: 107,
    nameArabic: 'الماعون',
    namePersian: 'ماعون',
    nameEnglish: 'Al-Ma\'un',
    revelationType: 'Makki',
    verseCount: 7,
  ),
  SurahsCompanion.insert(
    id: const Value(108),
    number: 108,
    nameArabic: 'الكوثر',
    namePersian: 'کوثر',
    nameEnglish: 'Al-Kawthar',
    revelationType: 'Makki',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: const Value(109),
    number: 109,
    nameArabic: 'الكافرون',
    namePersian: 'کافرون',
    nameEnglish: 'Al-Kafirun',
    revelationType: 'Makki',
    verseCount: 6,
  ),
  SurahsCompanion.insert(
    id: const Value(110),
    number: 110,
    nameArabic: 'النصر',
    namePersian: 'نصر',
    nameEnglish: 'An-Nasr',
    revelationType: 'Madani',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: const Value(111),
    number: 111,
    nameArabic: 'المسد',
    namePersian: 'مسد',
    nameEnglish: 'Al-Masad',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: const Value(112),
    number: 112,
    nameArabic: 'الإخلاص',
    namePersian: 'اخلاص',
    nameEnglish: 'Al-Ikhlas',
    revelationType: 'Makki',
    verseCount: 4,
  ),
  SurahsCompanion.insert(
    id: const Value(113),
    number: 113,
    nameArabic: 'الفلق',
    namePersian: 'فلق',
    nameEnglish: 'Al-Falaq',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: const Value(114),
    number: 114,
    nameArabic: 'الناس',
    namePersian: 'ناس',
    nameEnglish: 'An-Nas',
    revelationType: 'Makki',
    verseCount: 6,
  ),
];
