import 'package:drift/drift.dart';
import 'app_database.dart';

final List<SurahsCompanion> initialSurahsList = [
  SurahsCompanion.insert(
    id: Value(1),
    number: 1,
    nameArabic: 'الفاتحة',
    namePersian: 'حمد (گشایش)',
    nameEnglish: 'Al-Fatihah',
    revelationType: 'Makki',
    verseCount: 7,
  ),
  SurahsCompanion.insert(
    id: Value(2),
    number: 2,
    nameArabic: 'البقرة',
    namePersian: 'بقره (گاو ماده)',
    nameEnglish: 'Al-Baqarah',
    revelationType: 'Madani',
    verseCount: 286,
  ),
  SurahsCompanion.insert(
    id: Value(3),
    number: 3,
    nameArabic: 'آل عمران',
    namePersian: 'آل عمران (خاندان عمران)',
    nameEnglish: 'Ali \'Imran',
    revelationType: 'Madani',
    verseCount: 200,
  ),
  SurahsCompanion.insert(
    id: Value(4),
    number: 4,
    nameArabic: 'النساء',
    namePersian: 'نساء (زنان)',
    nameEnglish: 'An-Nisa',
    revelationType: 'Madani',
    verseCount: 176,
  ),
  SurahsCompanion.insert(
    id: Value(5),
    number: 5,
    nameArabic: 'المائدة',
    namePersian: 'مائده (سفره غذا)',
    nameEnglish: 'Al-Ma\'idah',
    revelationType: 'Madani',
    verseCount: 120,
  ),
  SurahsCompanion.insert(
    id: Value(6),
    number: 6,
    nameArabic: 'الأنعام',
    namePersian: 'انعام (چهارپایان)',
    nameEnglish: 'Al-An\'am',
    revelationType: 'Makki',
    verseCount: 165,
  ),
  SurahsCompanion.insert(
    id: Value(7),
    number: 7,
    nameArabic: 'الأعراف',
    namePersian: 'اعراف (بلندی‌ها)',
    nameEnglish: 'Al-A\'raf',
    revelationType: 'Makki',
    verseCount: 206,
  ),
  SurahsCompanion.insert(
    id: Value(8),
    number: 8,
    nameArabic: 'الأنفال',
    namePersian: 'انفال (غنایم)',
    nameEnglish: 'Al-Anfal',
    revelationType: 'Madani',
    verseCount: 75,
  ),
  SurahsCompanion.insert(
    id: Value(9),
    number: 9,
    nameArabic: 'التوبة',
    namePersian: 'توبه (توبه‌پذیری)',
    nameEnglish: 'At-Tawbah',
    revelationType: 'Madani',
    verseCount: 129,
  ),
  SurahsCompanion.insert(
    id: Value(10),
    number: 10,
    nameArabic: 'يونس',
    namePersian: 'یونس (حضرت یونس)',
    nameEnglish: 'Yunus',
    revelationType: 'Makki',
    verseCount: 109,
  ),
  SurahsCompanion.insert(
    id: Value(11),
    number: 11,
    nameArabic: 'هود',
    namePersian: 'هود (حضرت هود)',
    nameEnglish: 'Hud',
    revelationType: 'Makki',
    verseCount: 123,
  ),
  SurahsCompanion.insert(
    id: Value(12),
    number: 12,
    nameArabic: 'يوسف',
    namePersian: 'یوسف (حضرت یوسف)',
    nameEnglish: 'Yusuf',
    revelationType: 'Makki',
    verseCount: 111,
  ),
  SurahsCompanion.insert(
    id: Value(13),
    number: 13,
    nameArabic: 'الرعد',
    namePersian: 'رعد (رعد و برق)',
    nameEnglish: 'Ar-Ra\'d',
    revelationType: 'Madani',
    verseCount: 43,
  ),
  SurahsCompanion.insert(
    id: Value(14),
    number: 14,
    nameArabic: 'إبراهيم',
    namePersian: 'ابراهیم (حضرت ابراهیم)',
    nameEnglish: 'Ibrahim',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: Value(15),
    number: 15,
    nameArabic: 'الحجر',
    namePersian: 'حجر (سرزمین حجر)',
    nameEnglish: 'Al-Hijr',
    revelationType: 'Makki',
    verseCount: 99,
  ),
  SurahsCompanion.insert(
    id: Value(16),
    number: 16,
    nameArabic: 'النحل',
    namePersian: 'نحل (زنبور عسل)',
    nameEnglish: 'An-Nahl',
    revelationType: 'Makki',
    verseCount: 128,
  ),
  SurahsCompanion.insert(
    id: Value(17),
    number: 17,
    nameArabic: 'الإسراء',
    namePersian: 'اسراء (معراج/سیر شبانه)',
    nameEnglish: 'Al-Isra',
    revelationType: 'Makki',
    verseCount: 111,
  ),
  SurahsCompanion.insert(
    id: Value(18),
    number: 18,
    nameArabic: 'الكهف',
    namePersian: 'کهف (غار)',
    nameEnglish: 'Al-Kahf',
    revelationType: 'Makki',
    verseCount: 110,
  ),
  SurahsCompanion.insert(
    id: Value(19),
    number: 19,
    nameArabic: 'مريم',
    namePersian: 'مریم (حضرت مریم)',
    nameEnglish: 'Maryam',
    revelationType: 'Makki',
    verseCount: 98,
  ),
  SurahsCompanion.insert(
    id: Value(20),
    number: 20,
    nameArabic: 'طه',
    namePersian: 'طه',
    nameEnglish: 'Taha',
    revelationType: 'Makki',
    verseCount: 135,
  ),
  SurahsCompanion.insert(
    id: Value(21),
    number: 21,
    nameArabic: 'الأنبياء',
    namePersian: 'انبیاء (پیامبران)',
    nameEnglish: 'Al-Anbiya',
    revelationType: 'Makki',
    verseCount: 112,
  ),
  SurahsCompanion.insert(
    id: Value(22),
    number: 22,
    nameArabic: 'الحج',
    namePersian: 'حج (زیارت خانه خدا)',
    nameEnglish: 'Al-Hajj',
    revelationType: 'Madani',
    verseCount: 78,
  ),
  SurahsCompanion.insert(
    id: Value(23),
    number: 23,
    nameArabic: 'المؤمنون',
    namePersian: 'مؤمنون (مؤمنان)',
    nameEnglish: 'Al-Mu\'minun',
    revelationType: 'Makki',
    verseCount: 118,
  ),
  SurahsCompanion.insert(
    id: Value(24),
    number: 24,
    nameArabic: 'النور',
    namePersian: 'نور',
    nameEnglish: 'An-Nur',
    revelationType: 'Madani',
    verseCount: 64,
  ),
  SurahsCompanion.insert(
    id: Value(25),
    number: 25,
    nameArabic: 'الفرقان',
    namePersian: 'فرقان (جداسازنده حق از باطل)',
    nameEnglish: 'Al-Furqan',
    revelationType: 'Makki',
    verseCount: 77,
  ),
  SurahsCompanion.insert(
    id: Value(26),
    number: 26,
    nameArabic: 'الشعراء',
    namePersian: 'شعراء (شاعران)',
    nameEnglish: 'Ash-Shu\'ara',
    revelationType: 'Makki',
    verseCount: 227,
  ),
  SurahsCompanion.insert(
    id: Value(27),
    number: 27,
    nameArabic: 'النمل',
    namePersian: 'نمل (مورچه)',
    nameEnglish: 'An-Naml',
    revelationType: 'Makki',
    verseCount: 93,
  ),
  SurahsCompanion.insert(
    id: Value(28),
    number: 28,
    nameArabic: 'القصص',
    namePersian: 'قصص (داستان‌ها)',
    nameEnglish: 'Al-Qasas',
    revelationType: 'Makki',
    verseCount: 88,
  ),
  SurahsCompanion.insert(
    id: Value(29),
    number: 29,
    nameArabic: 'العنكبوت',
    namePersian: 'عنکبوت',
    nameEnglish: 'Al-\'Ankabut',
    revelationType: 'Makki',
    verseCount: 69,
  ),
  SurahsCompanion.insert(
    id: Value(30),
    number: 30,
    nameArabic: 'الروم',
    namePersian: 'روم (رومیان)',
    nameEnglish: 'Ar-Rum',
    revelationType: 'Makki',
    verseCount: 60,
  ),
  SurahsCompanion.insert(
    id: Value(31),
    number: 31,
    nameArabic: 'لقمان',
    namePersian: 'لقمان (حضرت لقمان)',
    nameEnglish: 'Luqman',
    revelationType: 'Makki',
    verseCount: 34,
  ),
  SurahsCompanion.insert(
    id: Value(32),
    number: 32,
    nameArabic: 'السجدة',
    namePersian: 'سجده',
    nameEnglish: 'As-Sajdah',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: Value(33),
    number: 33,
    nameArabic: 'الأحزاب',
    namePersian: 'احزاب (گروه‌ها)',
    nameEnglish: 'Al-Ahzab',
    revelationType: 'Madani',
    verseCount: 73,
  ),
  SurahsCompanion.insert(
    id: Value(34),
    number: 34,
    nameArabic: 'سبإ',
    namePersian: 'سبأ (قوم سبأ)',
    nameEnglish: 'Saba',
    revelationType: 'Makki',
    verseCount: 54,
  ),
  SurahsCompanion.insert(
    id: Value(35),
    number: 35,
    nameArabic: 'فاطر',
    namePersian: 'فاطر (آفریننده)',
    nameEnglish: 'Fatir',
    revelationType: 'Makki',
    verseCount: 45,
  ),
  SurahsCompanion.insert(
    id: Value(36),
    number: 36,
    nameArabic: 'يس',
    namePersian: 'یس',
    nameEnglish: 'Ya-Sin',
    revelationType: 'Makki',
    verseCount: 83,
  ),
  SurahsCompanion.insert(
    id: Value(37),
    number: 37,
    nameArabic: 'الصافات',
    namePersian: 'صافات (صف‌کشیدگان)',
    nameEnglish: 'As-Saffat',
    revelationType: 'Makki',
    verseCount: 182,
  ),
  SurahsCompanion.insert(
    id: Value(38),
    number: 38,
    nameArabic: 'ص',
    namePersian: 'ص',
    nameEnglish: 'Sad',
    revelationType: 'Makki',
    verseCount: 88,
  ),
  SurahsCompanion.insert(
    id: Value(39),
    number: 39,
    nameArabic: 'الزمر',
    namePersian: 'زمر (گروه‌ها/دسته‌ها)',
    nameEnglish: 'Az-Zumar',
    revelationType: 'Makki',
    verseCount: 75,
  ),
  SurahsCompanion.insert(
    id: Value(40),
    number: 40,
    nameArabic: 'غافر',
    namePersian: 'غافر (آمرزنده)',
    nameEnglish: 'Ghafir',
    revelationType: 'Makki',
    verseCount: 85,
  ),
  SurahsCompanion.insert(
    id: Value(41),
    number: 41,
    nameArabic: 'فصلت',
    namePersian: 'فصلت (بخش‌بندی شده)',
    nameEnglish: 'Fussilat',
    revelationType: 'Makki',
    verseCount: 54,
  ),
  SurahsCompanion.insert(
    id: Value(42),
    number: 42,
    nameArabic: 'الشورى',
    namePersian: 'شوری (مشورت)',
    nameEnglish: 'Ash-Shura',
    revelationType: 'Makki',
    verseCount: 53,
  ),
  SurahsCompanion.insert(
    id: Value(43),
    number: 43,
    nameArabic: 'الزخرف',
    namePersian: 'زخرف (طلا و زیور)',
    nameEnglish: 'Az-Zukhruf',
    revelationType: 'Makki',
    verseCount: 89,
  ),
  SurahsCompanion.insert(
    id: Value(44),
    number: 44,
    nameArabic: 'الدخان',
    namePersian: 'دخان (دود)',
    nameEnglish: 'Ad-Dukhan',
    revelationType: 'Makki',
    verseCount: 59,
  ),
  SurahsCompanion.insert(
    id: Value(45),
    number: 45,
    nameArabic: 'الجاثية',
    namePersian: 'جاثیه (به زانو درآمده)',
    nameEnglish: 'Al-Jathiyah',
    revelationType: 'Makki',
    verseCount: 37,
  ),
  SurahsCompanion.insert(
    id: Value(46),
    number: 46,
    nameArabic: 'الأحقاف',
    namePersian: 'احقاف (شنزارها)',
    nameEnglish: 'Al-Ahqaf',
    revelationType: 'Makki',
    verseCount: 35,
  ),
  SurahsCompanion.insert(
    id: Value(47),
    number: 47,
    nameArabic: 'محمد',
    namePersian: 'محمد (پیامبر اکرم ص)',
    nameEnglish: 'Muhammad',
    revelationType: 'Madani',
    verseCount: 38,
  ),
  SurahsCompanion.insert(
    id: Value(48),
    number: 48,
    nameArabic: 'الفتح',
    namePersian: 'فتح (پیروزی)',
    nameEnglish: 'Al-Fath',
    revelationType: 'Madani',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: Value(49),
    number: 49,
    nameArabic: 'الحجرات',
    namePersian: 'حجرات (حجره‌ها)',
    nameEnglish: 'Al-Hujurat',
    revelationType: 'Madani',
    verseCount: 18,
  ),
  SurahsCompanion.insert(
    id: Value(50),
    number: 50,
    nameArabic: 'ق',
    namePersian: 'ق',
    nameEnglish: 'Qaf',
    revelationType: 'Makki',
    verseCount: 45,
  ),
  SurahsCompanion.insert(
    id: Value(51),
    number: 51,
    nameArabic: 'الذاريات',
    namePersian: 'ذاریات (بادهای پراکنده‌کننده)',
    nameEnglish: 'Adh-Dhariyat',
    revelationType: 'Makki',
    verseCount: 60,
  ),
  SurahsCompanion.insert(
    id: Value(52),
    number: 52,
    nameArabic: 'الطور',
    namePersian: 'طور (کوه طور)',
    nameEnglish: 'At-Tur',
    revelationType: 'Makki',
    verseCount: 49,
  ),
  SurahsCompanion.insert(
    id: Value(53),
    number: 53,
    nameArabic: 'النجم',
    namePersian: 'نجم (ستاره)',
    nameEnglish: 'An-Najm',
    revelationType: 'Makki',
    verseCount: 62,
  ),
  SurahsCompanion.insert(
    id: Value(54),
    number: 54,
    nameArabic: 'القمر',
    namePersian: 'قمر (ماه)',
    nameEnglish: 'Al-Qamar',
    revelationType: 'Makki',
    verseCount: 55,
  ),
  SurahsCompanion.insert(
    id: Value(55),
    number: 55,
    nameArabic: 'الرحمن',
    namePersian: 'الرحمن (بخشنده)',
    nameEnglish: 'Ar-Rahman',
    revelationType: 'Madani',
    verseCount: 78,
  ),
  SurahsCompanion.insert(
    id: Value(56),
    number: 56,
    nameArabic: 'الواقعة',
    namePersian: 'واقعه (رویداد بزرگ)',
    nameEnglish: 'Al-Waqi\'ah',
    revelationType: 'Makki',
    verseCount: 96,
  ),
  SurahsCompanion.insert(
    id: Value(57),
    number: 57,
    nameArabic: 'الحديد',
    namePersian: 'حديد (آهن)',
    nameEnglish: 'Al-Hadid',
    revelationType: 'Madani',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: Value(58),
    number: 58,
    nameArabic: 'المجادلة',
    namePersian: 'مجادله (زن مجادله‌کننده)',
    nameEnglish: 'Al-Mujadila',
    revelationType: 'Madani',
    verseCount: 22,
  ),
  SurahsCompanion.insert(
    id: Value(59),
    number: 59,
    nameArabic: 'الحشر',
    namePersian: 'حشر (کوچ دادن/گردآوری)',
    nameEnglish: 'Al-Hashr',
    revelationType: 'Madani',
    verseCount: 24,
  ),
  SurahsCompanion.insert(
    id: Value(60),
    number: 60,
    nameArabic: 'الممتحنة',
    namePersian: 'ممتحنه (زن آزموده‌شده)',
    nameEnglish: 'Al-Mumtahanah',
    revelationType: 'Madani',
    verseCount: 13,
  ),
  SurahsCompanion.insert(
    id: Value(61),
    number: 61,
    nameArabic: 'الصف',
    namePersian: 'صف (صف‌کشیدن)',
    nameEnglish: 'As-Saff',
    revelationType: 'Madani',
    verseCount: 14,
  ),
  SurahsCompanion.insert(
    id: Value(62),
    number: 62,
    nameArabic: 'الجمعة',
    namePersian: 'جمعه (روز جمعه)',
    nameEnglish: 'Al-Jumu\'ah',
    revelationType: 'Madani',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: Value(63),
    number: 63,
    nameArabic: 'المنافقون',
    namePersian: 'منافقون (منافقان)',
    nameEnglish: 'Al-Munafiqun',
    revelationType: 'Madani',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: Value(64),
    number: 64,
    nameArabic: 'التغابن',
    namePersian: 'تغابن (مغابون شدن/حسرت)',
    nameEnglish: 'At-Taghabun',
    revelationType: 'Madani',
    verseCount: 18,
  ),
  SurahsCompanion.insert(
    id: Value(65),
    number: 65,
    nameArabic: 'الطلاق',
    namePersian: 'طلاق',
    nameEnglish: 'At-Talaq',
    revelationType: 'Madani',
    verseCount: 12,
  ),
  SurahsCompanion.insert(
    id: Value(66),
    number: 66,
    nameArabic: 'التحريم',
    namePersian: 'تحریم (حرام ساختن)',
    nameEnglish: 'At-Tahrim',
    revelationType: 'Madani',
    verseCount: 12,
  ),
  SurahsCompanion.insert(
    id: Value(67),
    number: 67,
    nameArabic: 'الملك',
    namePersian: 'ملک (فرمانروایی)',
    nameEnglish: 'Al-Mulk',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: Value(68),
    number: 68,
    nameArabic: 'القلم',
    namePersian: 'قلم',
    nameEnglish: 'Al-Qalam',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: Value(69),
    number: 69,
    nameArabic: 'الحاقة',
    namePersian: 'حاقه (روز تحقق/قیامت)',
    nameEnglish: 'Al-Haqqah',
    revelationType: 'Makki',
    verseCount: 52,
  ),
  SurahsCompanion.insert(
    id: Value(70),
    number: 70,
    nameArabic: 'المعارج',
    namePersian: 'معارج (درجات عروج)',
    nameEnglish: 'Al-Ma\'arij',
    revelationType: 'Makki',
    verseCount: 44,
  ),
  SurahsCompanion.insert(
    id: Value(71),
    number: 71,
    nameArabic: 'نوح',
    namePersian: 'نوح (حضرت نوح)',
    nameEnglish: 'Nuh',
    revelationType: 'Makki',
    verseCount: 28,
  ),
  SurahsCompanion.insert(
    id: Value(72),
    number: 72,
    nameArabic: 'الجن',
    namePersian: 'جن',
    nameEnglish: 'Al-Jinn',
    revelationType: 'Makki',
    verseCount: 28,
  ),
  SurahsCompanion.insert(
    id: Value(73),
    number: 73,
    nameArabic: 'المزمل',
    namePersian: 'مزمل (جامه‌به‌خود‌پیچیده)',
    nameEnglish: 'Al-Muzzammil',
    revelationType: 'Makki',
    verseCount: 20,
  ),
  SurahsCompanion.insert(
    id: Value(74),
    number: 74,
    nameArabic: 'المدثر',
    namePersian: 'مدثر (جامه جامه بپوشنده)',
    nameEnglish: 'Al-Muddaththir',
    revelationType: 'Makki',
    verseCount: 56,
  ),
  SurahsCompanion.insert(
    id: Value(75),
    number: 75,
    nameArabic: 'القيامة',
    namePersian: 'قیامت',
    nameEnglish: 'Al-Qiyamah',
    revelationType: 'Makki',
    verseCount: 40,
  ),
  SurahsCompanion.insert(
    id: Value(76),
    number: 76,
    nameArabic: 'الإنسان',
    namePersian: 'انسان (دهر)',
    nameEnglish: 'Al-Insan',
    revelationType: 'Madani',
    verseCount: 31,
  ),
  SurahsCompanion.insert(
    id: Value(77),
    number: 77,
    nameArabic: 'المرسلات',
    namePersian: 'مرسلات (فرستادگان)',
    nameEnglish: 'Al-Mursalat',
    revelationType: 'Makki',
    verseCount: 50,
  ),
  SurahsCompanion.insert(
    id: Value(78),
    number: 78,
    nameArabic: 'النبإ',
    namePersian: 'نبأ (خبر بزرگ)',
    nameEnglish: 'An-Naba',
    revelationType: 'Makki',
    verseCount: 40,
  ),
  SurahsCompanion.insert(
    id: Value(79),
    number: 79,
    nameArabic: 'النازعات',
    namePersian: 'نازعات (فرشتگان جان‌ستان)',
    nameEnglish: 'An-Nazi\'at',
    revelationType: 'Makki',
    verseCount: 46,
  ),
  SurahsCompanion.insert(
    id: Value(80),
    number: 80,
    nameArabic: 'عبس',
    namePersian: 'عبس (چهره درهم کشید)',
    nameEnglish: '\'Abasa',
    revelationType: 'Makki',
    verseCount: 42,
  ),
  SurahsCompanion.insert(
    id: Value(81),
    number: 81,
    nameArabic: 'التكوير',
    namePersian: 'تکویر (درهم پیچیدن تاریکی)',
    nameEnglish: 'At-Takwir',
    revelationType: 'Makki',
    verseCount: 29,
  ),
  SurahsCompanion.insert(
    id: Value(82),
    number: 82,
    nameArabic: 'الإنفطار',
    namePersian: 'انفطار (شکافته شدن آسمان)',
    nameEnglish: 'Al-Infitar',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: Value(83),
    number: 83,
    nameArabic: 'المطففين',
    namePersian: 'مطففین (کم‌فروشان)',
    nameEnglish: 'Al-Mutaffifin',
    revelationType: 'Makki',
    verseCount: 36,
  ),
  SurahsCompanion.insert(
    id: Value(84),
    number: 84,
    nameArabic: 'الإنشقاق',
    namePersian: 'انشقاق (از هم شکافتن)',
    nameEnglish: 'Al-Inshiqaq',
    revelationType: 'Makki',
    verseCount: 25,
  ),
  SurahsCompanion.insert(
    id: Value(85),
    number: 85,
    nameArabic: 'البروج',
    namePersian: 'بروج (برج‌ها)',
    nameEnglish: 'Al-Buruj',
    revelationType: 'Makki',
    verseCount: 22,
  ),
  SurahsCompanion.insert(
    id: Value(86),
    number: 86,
    nameArabic: 'الطارق',
    namePersian: 'طارق (ستاره شبانگاه)',
    nameEnglish: 'At-Tariq',
    revelationType: 'Makki',
    verseCount: 17,
  ),
  SurahsCompanion.insert(
    id: Value(87),
    number: 87,
    nameArabic: 'الأعلى',
    namePersian: 'اعلی (والاترین)',
    nameEnglish: 'Al-A\'la',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: Value(88),
    number: 88,
    nameArabic: 'الغاشية',
    namePersian: 'غاشیه (حادثه فراگیر/قیامت)',
    nameEnglish: 'Al-Ghashiyah',
    revelationType: 'Makki',
    verseCount: 26,
  ),
  SurahsCompanion.insert(
    id: Value(89),
    number: 89,
    nameArabic: 'الفجر',
    namePersian: 'فجر (سپیده‌دم)',
    nameEnglish: 'Al-Fajr',
    revelationType: 'Makki',
    verseCount: 30,
  ),
  SurahsCompanion.insert(
    id: Value(90),
    number: 90,
    nameArabic: 'البلد',
    namePersian: 'بلد (شهر)',
    nameEnglish: 'Al-Balad',
    revelationType: 'Makki',
    verseCount: 20,
  ),
  SurahsCompanion.insert(
    id: Value(91),
    number: 91,
    nameArabic: 'الشمس',
    namePersian: 'شمس (خورشید)',
    nameEnglish: 'Ash-Shams',
    revelationType: 'Makki',
    verseCount: 15,
  ),
  SurahsCompanion.insert(
    id: Value(92),
    number: 92,
    nameArabic: 'الليل',
    namePersian: 'لیل (شب)',
    nameEnglish: 'Al-Layl',
    revelationType: 'Makki',
    verseCount: 21,
  ),
  SurahsCompanion.insert(
    id: Value(93),
    number: 93,
    nameArabic: 'الضحى',
    namePersian: 'ضحی (چاشتگاه/روشنایی روز)',
    nameEnglish: 'Ad-Duha',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: Value(94),
    number: 94,
    nameArabic: 'الشرح',
    namePersian: 'شرح (گشایش سینه)',
    nameEnglish: 'Ash-Sharh',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: Value(95),
    number: 95,
    nameArabic: 'التين',
    namePersian: 'تین (انجیر)',
    nameEnglish: 'At-Tin',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: Value(96),
    number: 96,
    nameArabic: 'العلق',
    namePersian: 'علق (خون بسته)',
    nameEnglish: 'Al-\'Alaq',
    revelationType: 'Makki',
    verseCount: 19,
  ),
  SurahsCompanion.insert(
    id: Value(97),
    number: 97,
    nameArabic: 'القدر',
    namePersian: 'قدر (شب قدر)',
    nameEnglish: 'Al-Qadr',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: Value(98),
    number: 98,
    nameArabic: 'البينة',
    namePersian: 'بینه (دلیل آشکار)',
    nameEnglish: 'Al-Bayyinah',
    revelationType: 'Madani',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: Value(99),
    number: 99,
    nameArabic: 'الزلزلة',
    namePersian: 'زلزله (زمین‌لرزه)',
    nameEnglish: 'Az-Zalzalah',
    revelationType: 'Madani',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: Value(100),
    number: 100,
    nameArabic: 'العاديات',
    namePersian: 'عادیات (اسبان تاخت‌پیشه)',
    nameEnglish: 'Al-\'Adiyat',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: Value(101),
    number: 101,
    nameArabic: 'القارعة',
    namePersian: 'قارعه (حادثه کوبنده/قیامت)',
    nameEnglish: 'Al-Qari\'ah',
    revelationType: 'Makki',
    verseCount: 11,
  ),
  SurahsCompanion.insert(
    id: Value(102),
    number: 102,
    nameArabic: 'التكاثر',
    namePersian: 'تکاثر (افزون‌طلبی)',
    nameEnglish: 'At-Takathur',
    revelationType: 'Makki',
    verseCount: 8,
  ),
  SurahsCompanion.insert(
    id: Value(103),
    number: 103,
    nameArabic: 'العصر',
    namePersian: 'عصر (زمانه)',
    nameEnglish: 'Al-\'Asr',
    revelationType: 'Makki',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: Value(104),
    number: 104,
    nameArabic: 'الهمزة',
    namePersian: 'همزه (عیب‌جو)',
    nameEnglish: 'Al-Humazah',
    revelationType: 'Makki',
    verseCount: 9,
  ),
  SurahsCompanion.insert(
    id: Value(105),
    number: 105,
    nameArabic: 'الفيل',
    namePersian: 'فیل (سپاه فیل)',
    nameEnglish: 'Al-Fil',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: Value(106),
    number: 106,
    nameArabic: 'قريش',
    namePersian: 'قریش (قبیله قریش)',
    nameEnglish: 'Quraysh',
    revelationType: 'Makki',
    verseCount: 4,
  ),
  SurahsCompanion.insert(
    id: Value(107),
    number: 107,
    nameArabic: 'الماعون',
    namePersian: 'ماعون (وسایل احتیاج/کمک)',
    nameEnglish: 'Al-Ma\'un',
    revelationType: 'Makki',
    verseCount: 7,
  ),
  SurahsCompanion.insert(
    id: Value(108),
    number: 108,
    nameArabic: 'الكوثر',
    namePersian: 'کوثر (خیر فراوان)',
    nameEnglish: 'Al-Kawthar',
    revelationType: 'Makki',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: Value(109),
    number: 109,
    nameArabic: 'الكافرون',
    namePersian: 'کافرون (کافران)',
    nameEnglish: 'Al-Kafirun',
    revelationType: 'Makki',
    verseCount: 6,
  ),
  SurahsCompanion.insert(
    id: Value(110),
    number: 110,
    nameArabic: 'النصر',
    namePersian: 'نصر (یاری و پیروزی)',
    nameEnglish: 'An-Nasr',
    revelationType: 'Madani',
    verseCount: 3,
  ),
  SurahsCompanion.insert(
    id: Value(111),
    number: 111,
    nameArabic: 'المسد',
    namePersian: 'مسد (ریف/ریسمان خرمابن)',
    nameEnglish: 'Al-Masad',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: Value(112),
    number: 112,
    nameArabic: 'الإخلاص',
    namePersian: 'اخلاص (توحید)',
    nameEnglish: 'Al-Ikhlas',
    revelationType: 'Makki',
    verseCount: 4,
  ),
  SurahsCompanion.insert(
    id: Value(113),
    number: 113,
    nameArabic: 'الفلق',
    namePersian: 'فلق (سپیده‌دم)',
    nameEnglish: 'Al-Falaq',
    revelationType: 'Makki',
    verseCount: 5,
  ),
  SurahsCompanion.insert(
    id: Value(114),
    number: 114,
    nameArabic: 'الناس',
    namePersian: 'ناس (مردم)',
    nameEnglish: 'An-Nas',
    revelationType: 'Makki',
    verseCount: 6,
  ),
];
