import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('fa', 'IR'));
  }

  bool get isPersian => locale.languageCode == 'fa';
  TextDirection get textDirection => isPersian ? TextDirection.rtl : TextDirection.ltr;

  static final Map<String, Map<String, String>> _localizedValues = {
    'fa': {
      'appTitle': 'پلتفرم جامع علوم و معارف قرآن',
      'surahs': 'سوره‌ها',
      'search': 'جستجو',
      'aiAssistant': 'دستیار هوشمند قرآن',
      'bookmarks': 'نشان‌شده‌ها',
      'settings': 'تنظیمات',
      'searchPlaceholder': 'جستجو در آیات، ترجمه‌ها و تفاسیر...',
      'askAiPlaceholder': 'سوال خود را درباره مفاهیم قرآن بپرسید...',
      'defaultTranslation': 'ترجمه آیت‌الله مکارم شیرازی',
      'defaultTafsir': 'تفسیر نمونه',
      'makki': 'مکی',
      'madani': 'مدنی',
      'versesCount': 'آیه',
      'relatedVerses': 'آیات مرتبط',
      'sourcesAndCitations': 'منابع و تفاسیر مستند',
      'language': 'زبان برنامه',
      'persian': 'فارسی',
      'english': 'English',
      'noBookmarks': 'هیچ آیه‌ای نشان نشده است.',
      'addBookmark': 'نشان کردن آیه',
      'removeBookmark': 'حذف نشان',
      'tafsir': 'تفسیر آیه',
      'tafsirNoor': 'تفسیر نور (استاد قرائتی)',
      'tafsirNemoneh': 'تفسیر نمونه (آیت‌الله مکارم شیرازی)',
      'tafsirAlmizan': 'تفسیر المیزان (علامه طباطبائی)',
      'tafsirIbnKathir': 'تفسیر ابن کثیر (انگلیسی)',
      'selectTafsir': 'انتخاب تفسیر',
      'copyTafsir': 'کپی متن تفسیر',
      'copiedToClipboard': 'متن تفسیر در حافظه کپی شد',
      'ayahTafsirHeader': 'تفسیر آیه',
      'page': 'صفحه',
      'juz': 'جزء',
      'verseSelectionAction': 'عملیات پیش‌فرض لمس آیه',
      'verseSelectionActionSubtitle': 'عملیاتی که با لمس آیه در متن سوره انجام می‌شود',
      'actionShowTafsir': 'مشاهده تفسیر',
      'actionPlayAudio': 'پخش تلاوت صوتی',
      'actionShowMenu': 'منوی سریع عملیات',
      'defaultTafsirEdition': 'تفسیر پیش‌فرض',
      'defaultTafsirEditionSubtitle': 'تفسیر برگزیده برای مطالعه و باز شدن سریع',
      'quickActions': 'عملیات آیه',
      'listenAyah': 'شنیدن تلاوت',
      'copyAyah': 'کپی متن آیه',
      'shareAyah': 'اشتراک‌گذاری آیه',
      'ayahCopied': 'متن آیه در حافظه کپی شد',
      'keepScreenOn': 'روشن ماندن صفحه هنگام قرائت',
      'keepScreenOnSubtitle': 'جلوگیری از خاموش شدن خودکار صفحه هنگام مطالعه و تلاوت',
      'verseRepeat': 'تکرار آیه',
      'verseRepeatSubtitle': 'تعداد دفعات تکرار هر آیه پیش از رفتن به آیه بعد',
      'repeatOnce': 'یک‌بار (بدون تکرار)',
      'repeatTwice': '۲ بار تکرار',
      'repeatThreeTimes': '۳ بار تکرار (تجوید و تمرین)',
      'repeatFiveTimes': '۵ بار تکرار (حفظ قرآن)',
      'repeatTenTimes': '۱۰ بار تکرار (حفظ فشرده)',
      'repeatInfinite': 'تکرار مداوم (بی‌نهایت)',
      'downloadSurah': 'دانلود صوت سوره',
      'downloadSurahTooltip': 'دانلود تمام آیات این سوره جهت استفاده آفلاین',
      'downloadingSurah': 'در حال دانلود صوت سوره...',
      'surahDownloaded': 'صوت سوره با موفقیت دانلود شد',
      'surahDownloadedReady': 'صوت سوره به صورت آفلاین آماده است',
      'deleteSurahAudio': 'حذف فایل‌های صوتی سوره',
      'cancelDownload': 'لغو دانلود',
      'audioStorage': 'حافظه فایل‌های صوتی آفلاین',
      'clearAllAudio': 'پاکسازی تمام فایل‌های صوتی دانلودی',
      'confirmDeleteAudio': 'آیا مایل به حذف فایل‌های صوتی دانلودی هستید؟',
      'audioCleared': 'تمام فایل‌های صوتی آفلاین پاکسازی شدند',
      'khatmah': 'برنامه ختم قرآن',
      'khatmahSubtitle': 'برنامه‌ریزی روزانه و پیگیری پیشرفت ختم قرآن مجید',
      'startKhatmah': 'آغاز برنامه ختم جدید',
      'continueKhatmah': 'ادامه مطالعه',
      'continueFromPage': 'ادامه از صفحه',
      'khatmahProgress': 'پیشرفت ختم',
      'todayTarget': 'هدف امروز',
      'pagesRemaining': 'صفحه باقی‌مانده',
      'daysRemaining': 'روز باقی‌مانده',
      'dayStreak': 'روز مطالعه مداوم',
      'preset30Days': '۳۰ روزه (ماه رمضان - روزی ۱ جزء)',
      'preset60Days': '۶۰ روزه (۲ ماهه - روزی ۱۰ صفحه)',
      'preset90Days': '۹۰ روزه (۳ ماهه - روزی ۶.۷ صفحه)',
      'preset365Days': '۱ ساله (روزی ۱.۷ صفحه)',
      'markPageRead': 'ثبت مطالعه صفحه',
      'khatmahCompleted': 'تبریک! ختم قرآن با موفقیت انجام شد 🎉',
      'deleteKhatmah': 'حذف برنامه ختم',
      'verseRangeRepeat': 'تکرار بازه‌ای آیات (حفظ و تمرین)',
      'verseRangeRepeatSubtitle': 'تکرار مداوم مجموعه‌ای از آیات پشت سر هم جهت حفظ قرآن',
      'fromVerse': 'از آیه',
      'toVerse': 'تا آیه',
      'rangeCycles': 'تعداد دور تکرار کل بازه',
      'startRangeLoop': 'آغاز تکرار بازه',
      'stopRangeLoop': 'توقف تکرار بازه',
      'rangeActive': 'تکرار بازه فعال است',
      'cycle': 'دور',
      'presetNext5': '+۵ آیه',
      'presetNext10': '+۱۰ آیه',
      'wholeSurah': 'تمام سوره',
      'pageRepeat': 'تکرار صفحه قرآن (حفظ)',
      'pageRepeatSubtitle': 'تکرار مداوم یک صفحه کامل از قرآن جهت حفظ و تثبیت',
      'repeatModeVerses': 'بازه آیات',
      'repeatModePage': 'کل صفحه',
      'selectPage': 'انتخاب صفحه',
      'startPageLoop': 'آغاز تکرار صفحه',
      'stopPageLoop': 'توقف تکرار صفحه',
      'pageLoopActive': 'تکرار صفحه فعال است',
      'currentPage': 'صفحه فعلی',
      'nextPage': 'صفحه بعد',
      'previousPage': 'صفحه قبل',
      'pageCycles': 'تعداد دور تکرار صفحه',
      'quickPageJump': 'پرش سریع به صفحه',
      'goToPage': 'برو به صفحه',
      'enterPageNumber': 'شماره صفحه قرآن (۱ تا ۶۰۴)',
      'pageRangeHint': 'شماره صفحه معتبر بین ۱ تا ۶۰۴ است',
      'randomPage': 'صفحه تصادفی 🎲',
      'jumpDirectlyToPage': 'رفتن مستقیم به صفحه',
      'notesAndHighlights': 'یادداشت‌ها و هایلایت‌ها',
      'prayerTimesAndQibla': 'اوقات شرعی و قبله‌نما',
      'addNoteAndHighlight': 'ثبت یادداشت و هایلایت',
      'saveNote': 'ذخیره یادداشت',
      'highlightColor': 'رنگ هایلایت',
      'removeHighlight': 'حذف هایلایت',
      'personalNoteHint': 'تدبر، برداشت یا یادداشت شخصی خود را بنویسید...',
      'digitalTasbih': 'تسبیح‌شمار',
      'quranicDuas': 'ادعیه و ۴۰ ربنا',
      'sajdahAyah': 'آیه سجده‌دار',
      'wajibSajdah': 'سجده واجب',
      'mustahabSajdah': 'سجده مستحب',
      'sleepTimer': 'تایمر خواب',
      'createAyahCard': 'ساخت کارت تصویری و استوری',
      'aspectRatio': 'ابعاد کارت',
      'themeStyle': 'قالب و سبک طراحی',
      'endOfSurah': 'پایان سوره',
      'minutes': 'دقیقه',
      'hifzMode': 'حالت تمرین و حفظ',
      'hifzMaskAll': 'پوشاندن همه',
      'hifzRevealAll': 'آشکارسازی همه',
      'readingAnalytics': 'آمار و تقویم تلاوت',
      'quranQuiz': 'مسابقه و آزمون قرآنی',
      'quranIndex': 'فهرست جزء‌ها و ترتیب نزول',
      'smartBookmarks': 'نشان‌ها و مجموعه‌ها',
      'reminders': 'یادآورها و آیه روز',
      'tajweedGuide': 'راهنمای احکام تجوید',
      'quranTopics': 'نمایه موضوعی قرآن',
      'asmaulHusna': 'اسماء الحسنی (۹۹ نام خدا)',
      'islamicCalendar': 'تقویم اسلامی و مناسبت‌ها',
      'quranRoots': 'ریشه‌شناسی واژگان قرآن',
      'dailyAdhkar': 'اذکار و تعقیبات روزانه',
      'ziyaratSanctuary': 'زیارات و ادعیه شریفه',
      'quranParables': 'مَثَل‌های قرآن کریم',
      'wasiyyahBuilder': 'وصیت‌نامه شرعی و معنوی',
      'lastRead': 'آخرین مطالعه',
      'continueReading': 'ادامه مطالعه',
      'resumedAtAyah': 'ادامه از آیه',
      'lastReadVerse': 'آخرین آیه مطالعه‌شده',
      'clearHistory': 'پاکسازی تاریخچه',
    },
    'en': {
      'appTitle': 'Quran Exploration & RAG Platform',
      'surahs': 'Surahs',
      'search': 'Search',
      'aiAssistant': 'AI Assistant',
      'bookmarks': 'Bookmarks',
      'settings': 'Settings',
      'searchPlaceholder': 'Search verses, translations, and tafsir...',
      'askAiPlaceholder': 'Ask any conceptual question about the Quran...',
      'defaultTranslation': 'Dr. Mustafa Khattab (The Clear Quran)',
      'defaultTafsir': 'Tafsir Ibn Kathir',
      'makki': 'Makki',
      'madani': 'Madani',
      'versesCount': 'Verses',
      'relatedVerses': 'Related Verses',
      'sourcesAndCitations': 'Grounded Citations',
      'language': 'App Language',
      'persian': 'فارسی',
      'english': 'English',
      'noBookmarks': 'No bookmarked verses.',
      'addBookmark': 'Bookmark Verse',
      'removeBookmark': 'Remove Bookmark',
      'tafsir': 'Ayah Tafsir',
      'tafsirNoor': 'Tafsir Noor (Dr. Qara\'ati)',
      'tafsirNemoneh': 'Tafsir Nemoneh (Makarem Shirazi)',
      'tafsirAlmizan': 'Tafsir Al-Mizan (Allameh Tabataba\'i)',
      'tafsirIbnKathir': 'Tafsir Ibn Kathir (English)',
      'selectTafsir': 'Select Tafsir Edition',
      'copyTafsir': 'Copy Tafsir Text',
      'copiedToClipboard': 'Tafsir text copied to clipboard',
      'ayahTafsirHeader': 'Ayah Tafsir',
      'page': 'Page',
      'juz': 'Juz',
      'verseSelectionAction': 'Default Verse Tap Action',
      'verseSelectionActionSubtitle': 'Action executed when tapping on an ayah card',
      'actionShowTafsir': 'View Tafsir',
      'actionPlayAudio': 'Play Recitation',
      'actionShowMenu': 'Quick Actions Menu',
      'defaultTafsirEdition': 'Default Tafsir Edition',
      'defaultTafsirEditionSubtitle': 'Preferred commentary edition for Quran study',
      'quickActions': 'Ayah Actions',
      'listenAyah': 'Listen Recitation',
      'copyAyah': 'Copy Ayah',
      'shareAyah': 'Share Ayah',
      'ayahCopied': 'Ayah text copied to clipboard',
      'keepScreenOn': 'Keep Screen On While Reading',
      'keepScreenOnSubtitle': 'Prevent screen from sleeping during Quran study and recitation',
      'verseRepeat': 'Verse Repeat',
      'verseRepeatSubtitle': 'Number of times to repeat each verse before advancing',
      'repeatOnce': '1x (Play Once)',
      'repeatTwice': '2x (Repeat Twice)',
      'repeatThreeTimes': '3x (Tajweed Practice)',
      'repeatFiveTimes': '5x (Hifz / Memorization)',
      'repeatTenTimes': '10x (Intensive Memorization)',
      'repeatInfinite': 'Infinite Loop (∞)',
      'downloadSurah': 'Download Surah Audio',
      'downloadSurahTooltip': 'Download all verses of this Surah for offline playback',
      'downloadingSurah': 'Downloading Surah audio...',
      'surahDownloaded': 'Surah audio downloaded successfully',
      'surahDownloadedReady': 'Surah audio is ready for offline listening',
      'deleteSurahAudio': 'Delete Surah Audio Files',
      'cancelDownload': 'Cancel Download',
      'audioStorage': 'Offline Audio Storage',
      'clearAllAudio': 'Clear All Downloaded Audio',
      'confirmDeleteAudio': 'Are you sure you want to delete all downloaded audio files?',
      'audioCleared': 'All offline audio files cleared successfully',
      'khatmah': 'Quran Khatmah Plan',
      'khatmahSubtitle': 'Daily reading goals and progress tracker for the Holy Quran',
      'startKhatmah': 'Start New Khatmah Plan',
      'continueKhatmah': 'Continue Reading',
      'continueFromPage': 'Continue from Page',
      'khatmahProgress': 'Khatmah Progress',
      'todayTarget': 'Today\'s Target',
      'pagesRemaining': 'pages remaining',
      'daysRemaining': 'days left',
      'dayStreak': 'Day Reading Streak',
      'preset30Days': '30 Days (Ramadan - 1 Juz/day)',
      'preset60Days': '60 Days (2 Months - 10 pages/day)',
      'preset90Days': '90 Days (Quarterly - 6.7 pages/day)',
      'preset365Days': '1 Year (Annual - 1.7 pages/day)',
      'markPageRead': 'Log Page Completed',
      'khatmahCompleted': 'Congratulations! Quran Khatmah Completed 🎉',
      'deleteKhatmah': 'Delete Khatmah Plan',
      'verseRangeRepeat': 'Verse-Range Repeat (Hifz Mode)',
      'verseRangeRepeatSubtitle': 'Loop a custom block of verses repeatedly for memorization',
      'fromVerse': 'From Verse',
      'toVerse': 'To Verse',
      'rangeCycles': 'Range Loop Cycles',
      'startRangeLoop': 'Start Range Loop',
      'stopRangeLoop': 'Clear Range Loop',
      'rangeActive': 'Range Loop Active',
      'cycle': 'Cycle',
      'presetNext5': '+5 Verses',
      'presetNext10': '+10 Verses',
      'wholeSurah': 'Whole Surah',
      'pageRepeat': 'Quran Page Repeat (Hifz)',
      'pageRepeatSubtitle': 'Loop an entire Quran page repeatedly for memorization',
      'repeatModeVerses': 'Verse Range',
      'repeatModePage': 'Entire Page',
      'selectPage': 'Select Page',
      'startPageLoop': 'Start Page Loop',
      'stopPageLoop': 'Stop Page Loop',
      'pageLoopActive': 'Page Repeat Active',
      'currentPage': 'Current Page',
      'nextPage': 'Next Page',
      'previousPage': 'Previous Page',
      'pageCycles': 'Page Loop Cycles',
      'quickPageJump': 'Quick Page Jump',
      'goToPage': 'Go to Page',
      'enterPageNumber': 'Quran page number (1 to 604)',
      'pageRangeHint': 'Page number must be between 1 and 604',
      'randomPage': 'Random Page 🎲',
      'jumpDirectlyToPage': 'Jump directly to Page',
      'notesAndHighlights': 'Notes & Highlights',
      'prayerTimesAndQibla': 'Prayer Times & Qibla',
      'addNoteAndHighlight': 'Add Note & Highlight',
      'saveNote': 'Save Note',
      'highlightColor': 'Highlight Color',
      'removeHighlight': 'Remove Highlight',
      'personalNoteHint': 'Write your personal reflection or note here...',
      'digitalTasbih': 'Digital Tasbih',
      'quranicDuas': 'Quranic Duas',
      'sajdahAyah': 'Sajdah Ayah',
      'wajibSajdah': 'Obligatory Sajdah',
      'mustahabSajdah': 'Recommended Sajdah',
      'sleepTimer': 'Sleep Timer',
      'createAyahCard': 'Create Ayah Card & Story',
      'aspectRatio': 'Aspect Ratio',
      'themeStyle': 'Theme Style',
      'endOfSurah': 'End of Surah',
      'minutes': 'Minutes',
      'hifzMode': 'Hifz Practice Mode',
      'hifzMaskAll': 'Mask All',
      'hifzRevealAll': 'Reveal All',
      'readingAnalytics': 'Study & Reading Analytics',
      'quranQuiz': 'Quranic Quiz',
      'quranIndex': 'Juz & Revelation Index',
      'smartBookmarks': 'Smart Bookmarks',
      'reminders': 'Reminders & Daily Ayah',
      'tajweedGuide': 'Tajweed Rules Guide',
      'quranTopics': 'Thematic Quranic Topics',
      'asmaulHusna': 'Asmaul Husna (99 Names)',
      'islamicCalendar': 'Islamic Calendar & Events',
      'quranRoots': 'Quranic Root Words',
      'dailyAdhkar': 'Daily Adhkar & Duas',
      'ziyaratSanctuary': 'Sacred Ziyarat & Duas',
      'quranParables': 'Quranic Parables & Metaphors',
      'wasiyyahBuilder': 'Islamic Will & Testament',
      'lastRead': 'Last Read',
      'continueReading': 'Continue Reading',
      'resumedAtAyah': 'Resumed at Ayah',
      'lastReadVerse': 'Last Studied Ayah',
      'clearHistory': 'Clear History',
    },
  };

  String translate(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['fa']?[key] ?? key;
  }
}

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier() : super(const Locale('fa', 'IR'));

  void setPersian() {
    state = const Locale('fa', 'IR');
  }

  void setEnglish() {
    state = const Locale('en', 'US');
  }

  void toggleLanguage() {
    if (state.languageCode == 'fa') {
      setEnglish();
    } else {
      setPersian();
    }
  }
}

final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

final textDirectionProvider = Provider<TextDirection>((ref) {
  final locale = ref.watch(localeProvider);
  return locale.languageCode == 'fa' ? TextDirection.rtl : TextDirection.ltr;
});
